# Generated by Django 2.2.8 on 2020-03-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_text_long',
            field=models.CharField(default='', max_length=5200),
            preserve_default=False,
        ),
    ]
