# Generated by Django 2.2.4 on 2020-04-11 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_question_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='polls.Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text_long',
            field=models.CharField(default=None, max_length=5200),
        ),
    ]
